---


  - name: Creating mysql container
    docker_container:
      name: mysql
      image: mariadb
      env:
         MYSQL_ROOT_PASSWORD: "{{ root_pass }}"
         MYSQL_DATABASE: "{{ db_name }}"
         MYSQL_USER: "{{ db_user }}"
         MYSQL_PASSWORD: "{{ user_pass }}"
      networks:
        - name: "{{ network }}"
